import { digest } from './audit';

export interface ArtifactCatalogEntry {
  name: string;
  schema: string;
  format: 'json' | 'markdown';
  defaultPath: string;
  generateCommand: string;
  verifyCommand?: string;
  purpose: string;
}

export interface ArtifactCatalog {
  schema: 'airlock.artifact_catalog.v1';
  entries: ArtifactCatalogEntry[];
  catalogHash: string;
}

export function buildArtifactCatalog(): ArtifactCatalog {
  const entries: ArtifactCatalogEntry[] = [
    {
      name: 'Analytics schema',
      schema: 'airlock.analytics_schema.stage0.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-analytics-schema-airlock-roadmap.001.json',
      generateCommand: 'npm run analytics-schema -- airlock-roadmap.001',
      verifyCommand: 'npm run verify-analytics-schema -- ./artifacts/airlock-analytics-schema-airlock-roadmap.001.json',
      purpose: 'Stage 0 product analytics contract for measuring D7 return, pickem participation, transcript completion, and stage-gate metrics without accounts or private prompt storage.',
    },
    {
      name: 'Author intake registry',
      schema: 'airlock.author_intake_registry.stage1.preview.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-author-intake-registry-stage1-preview.001.json',
      generateCommand: 'npm run author-intake-registry -- stage1-preview.001',
      verifyCommand: 'npm run verify-author-intake-registry -- ./artifacts/airlock-author-intake-registry-stage1-preview.001.json',
      purpose: 'Stage 1 author intake gate artifact for validating manifests, prompt commitments, duplicate identity review, and the 100 active authored-agent target.',
    },
    {
      name: 'Audit bundle',
      schema: 'airlock.audit.stage0.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-audit-airlock-stage-zero-demo.json',
      generateCommand: 'npm run audit -- airlock-stage-zero-demo',
      verifyCommand: 'npm run verify-audit -- ./artifacts/airlock-audit-airlock-stage-zero-demo.json',
      purpose: 'Full deterministic match audit data: commitments, transcript, market snapshots, public snapshots, entropy, and tick commitments.',
    },
    {
      name: 'B2B feed packet',
      schema: 'airlock.b2b_feed_packet.stage2.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-b2b-feed-packet-airlock-stage-zero-demo.json',
      generateCommand: 'npm run b2b-feed-packet -- airlock-stage-zero-demo airlock-roadmap.001',
      verifyCommand: 'npm run verify-b2b-feed-packet -- ./artifacts/airlock-b2b-feed-packet-airlock-stage-zero-demo.json',
      purpose: 'Licensed-operator or media partner packet that bundles the certified event feed, market readiness gates, stage-gate policy, and no direct consumer betting posture.',
    },
    {
      name: 'Full verification bundle',
      schema: 'airlock.verify_all.local',
      format: 'json',
      defaultPath: './artifacts/',
      generateCommand: 'npm run verify-all',
      purpose: 'Single reviewer command that regenerates the core artifact set and runs deterministic verification checks in one pass.',
    },
    {
      name: 'Stage 0 evaluation',
      schema: 'airlock.stage0_evaluation.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-stage0-evaluation.json',
      generateCommand: 'npm run stage0-evaluation',
      verifyCommand: 'npm run verify-stage0-evaluation -- ./artifacts/airlock-stage0-evaluation.json',
      purpose: 'Reviewer-facing go/no-go summary combining balance, seed coverage, show pack readiness, and transcript legibility gates.',
    },
    {
      name: 'Balance patch schedule',
      schema: 'airlock.balance_patch_schedule.stage1.preview.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-balance-patch-schedule-stage1-preview.001.json',
      generateCommand: 'npm run balance-patch-schedule -- stage1-preview.001',
      verifyCommand: 'npm run verify-balance-patch-schedule -- ./artifacts/airlock-balance-patch-schedule-stage1-preview.001.json',
      purpose: 'Precommitted Stage 1 balance mutation schedule for P5-style anti-fragility without operator-discretionary patches.',
    },
    {
      name: 'Operator readiness',
      schema: 'airlock.operator_readiness.stage0.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-operator-readiness.json',
      generateCommand: 'npm run operator-readiness',
      verifyCommand: 'npm run verify-operator-readiness -- ./artifacts/airlock-operator-readiness.json',
      purpose: 'Single readiness checklist over Stage 0 product gates plus P1/P2/P4/P9 evidence artifacts.',
    },
    {
      name: 'Market readiness',
      schema: 'airlock.market_readiness.stage2.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-market-readiness-airlock-stage-zero-demo.json',
      generateCommand: 'npm run market-readiness -- airlock-stage-zero-demo',
      verifyCommand: 'npm run verify-market-readiness -- ./artifacts/airlock-market-readiness-airlock-stage-zero-demo.json',
      purpose: 'Stage 2 gate artifact that keeps real-money markets blocked unless counsel, jurisdiction, operator, and responsible-play evidence hashes are supplied.',
    },
    {
      name: 'Collusion controls',
      schema: 'airlock.collusion_controls.stage1.preview.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-collusion-controls-stage1-preview.001.json',
      generateCommand: 'npm run collusion-controls -- stage1-preview.001',
      verifyCommand: 'npm run verify-collusion-controls -- ./artifacts/airlock-collusion-controls-stage1-preview.001.json',
      purpose: 'Stage 1 anti-collusion economics artifact covering superlinear entry bonds, speech-sanitizer controls, throw-detection metrics, and escrow forfeiture paths.',
    },
    {
      name: 'Prompt reveal policy',
      schema: 'airlock.prompt_reveal_policy.stage1.preview.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-prompt-reveal-policy-stage1-preview.001.json',
      generateCommand: 'npm run prompt-reveal-policy -- stage1-preview.001',
      verifyCommand: 'npm run verify-prompt-reveal-policy -- ./artifacts/airlock-prompt-reveal-policy-stage1-preview.001.json',
      purpose: 'Stage 1 prompt reveal artifact for P3: pre-season commitments, auditor-only prompt access, challenge mediation, and two-season lagged public reveal.',
    },
    {
      name: 'Stage gate policy',
      schema: 'airlock.stage_gate_policy.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-stage-gate-policy-airlock-roadmap.001.json',
      generateCommand: 'npm run stage-gate-policy -- airlock-roadmap.001',
      verifyCommand: 'npm run verify-stage-gate-policy -- ./artifacts/airlock-stage-gate-policy-airlock-roadmap.001.json',
      purpose: 'Roadmap gate artifact for Show -> Ladder -> Market sequencing, explicit kill criteria, hold-stage decisions, and B2B-feed pivot conditions.',
    },
    {
      name: 'Challenge packet',
      schema: 'airlock.challenge.stage0.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-challenge-airlock-stage-zero-demo.json',
      generateCommand: 'npm run challenge -- airlock-stage-zero-demo',
      purpose: 'Single-file optimistic fairness packet containing an audit bundle and deterministic replay verification evidence.',
    },
    {
      name: 'Certified event feed',
      schema: 'airlock.certified_event_feed.stage0.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-event-feed-airlock-stage-zero-demo.json',
      generateCommand: 'npm run event-feed -- airlock-stage-zero-demo',
      verifyCommand: 'npm run verify-event-feed -- ./artifacts/airlock-event-feed-airlock-stage-zero-demo.json',
      purpose: 'Public transcript and market feed artifact for media or licensed-market partner review, with terminal-only role disclosure.',
    },
    {
      name: 'Match report',
      schema: 'airlock.report.stage0.markdown',
      format: 'markdown',
      defaultPath: './artifacts/airlock-report-airlock-stage-zero-demo.md',
      generateCommand: 'npm run report -- airlock-stage-zero-demo',
      purpose: 'Human-readable match archive with commitments, role reveal, public transcript, entropy ledger, and tick commitments.',
    },
    {
      name: 'Transcript quality report',
      schema: 'airlock.transcript_quality.stage0.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-transcript-quality-airlock-stage-zero-demo.json',
      generateCommand: 'npm run transcript-quality -- airlock-stage-zero-demo',
      verifyCommand: 'npm run verify-transcript-quality -- ./artifacts/airlock-transcript-quality-airlock-stage-zero-demo.json',
      purpose: 'Deterministic content-health report for speech, votes, reports, danger beats, repairs, and meeting density.',
    },
    {
      name: 'Reveal schedule',
      schema: 'airlock.reveal_schedule.stage0.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-reveal-schedule-airlock-stage-zero-demo.json',
      generateCommand: 'npm run reveal-schedule -- airlock-stage-zero-demo',
      verifyCommand: 'npm run verify-reveal-schedule -- ./artifacts/airlock-reveal-schedule-airlock-stage-zero-demo.json',
      purpose: 'Commit-before-render schedule with fixed public reveal delay for reviewing P2 timing and side-channel policy.',
    },
    {
      name: 'Role roadmap',
      schema: 'airlock.role_roadmap.stage1.preview.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-role-roadmap-airlock-role-roadmap.001.json',
      generateCommand: 'npm run role-roadmap -- airlock-role-roadmap.001',
      verifyCommand: 'npm run verify-role-roadmap -- ./artifacts/airlock-role-roadmap-airlock-role-roadmap.001.json',
      purpose: 'Stage 1 role-variety roadmap for P5 anti-fragility, keeping base-season roles fixed and gating future roles behind balance and market-impact review.',
    },
    {
      name: 'Sanitizer audit',
      schema: 'airlock.sanitizer_audit.stage0.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-sanitizer-audit-airlock-stage-zero-demo.json',
      generateCommand: 'npm run sanitizer-audit -- airlock-stage-zero-demo',
      verifyCommand: 'npm run verify-sanitizer-audit -- ./artifacts/airlock-sanitizer-audit-airlock-stage-zero-demo.json',
      purpose: 'Deterministic meeting-speech sanitizer audit for reviewing anti-steganography policy before agents receive speech.',
    },
    {
      name: 'Fallback drill',
      schema: 'airlock.fallback_drill.stage0.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-fallback-drill-airlock-stage-zero-demo.json',
      generateCommand: 'npm run fallback-drill -- airlock-stage-zero-demo',
      verifyCommand: 'npm run verify-fallback-drill -- ./artifacts/airlock-fallback-drill-airlock-stage-zero-demo.json',
      purpose: 'Deterministic timeout drill showing action, speech, vote, and micro-pool void fallbacks for inference failures.',
    },
    {
      name: 'Inference receipts',
      schema: 'airlock.inference_receipts.stage0.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-inference-receipts-airlock-stage-zero-demo.json',
      generateCommand: 'npm run inference-receipts -- airlock-stage-zero-demo',
      verifyCommand: 'npm run verify-inference-receipts -- ./artifacts/airlock-inference-receipts-airlock-stage-zero-demo.json',
      purpose: 'Speech-generation receipt log for P1-style optimistic fairness review: prompt hashes, output hashes, token counts, logprob commitments, and receipt hashes.',
    },
    {
      name: "Pick'em receipt",
      schema: 'airlock.pickem.stage0.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-pickem-airlock-stage-zero-demo.json',
      generateCommand: 'npm run pickem -- airlock-stage-zero-demo vanta kepler',
      verifyCommand: 'npm run verify-pickem -- ./artifacts/airlock-pickem-airlock-stage-zero-demo.json',
      purpose: "Spectator pick receipt with the selected suspects, actual Saboteurs, score, transcript hash, and receipt hash.",
    },
    {
      name: 'Balance summary',
      schema: 'airlock.balance.stage0.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-balance-ci.json',
      generateCommand: 'npm run balance:check',
      verifyCommand: 'npm run verify-balance -- ./artifacts/airlock-balance-ci.json',
      purpose: 'Batch simulator health report with win rates, match-length averages, terminal reasons, and Saboteur pair distribution.',
    },
    {
      name: 'Ladder preview',
      schema: 'airlock.ladder.stage1.preview.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-ladder-32.json',
      generateCommand: 'npm run ladder -- 32 stage-one-ci',
      verifyCommand: 'npm run verify-ladder -- ./artifacts/airlock-ladder-32.json',
      purpose: 'Stage 1 bridge artifact with deterministic Elo-style standings over repeated seeded matches.',
    },
    {
      name: 'Season manifest',
      schema: 'airlock.season.manifest.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-season-stage1-preview.001.json',
      generateCommand: 'npm run season -- stage1-preview.001',
      verifyCommand: 'npm run verify-season -- ./artifacts/airlock-season-stage1-preview.001.json',
      purpose: 'Locked preview-season policy manifest covering ruleset, model policy, authoring requirements, ladder settings, and audit policy.',
    },
    {
      name: 'Agent submission packet',
      schema: 'airlock.agent.submission.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-agent-submission.json',
      generateCommand: 'npm run submit-agent -- src/tests/fixtures/agents/vanta-author.json stage1-preview.001',
      verifyCommand: 'npm run verify-agent-submission -- ./artifacts/airlock-agent-submission.json',
      purpose: 'Stage 1 author intake packet containing a public manifest, validation output, target season hash, and submission hash.',
    },
    {
      name: 'Canonical seed index',
      schema: 'airlock.seed_index.stage0.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-seed-index.json',
      generateCommand: 'npm run seed-index',
      verifyCommand: 'npm run verify-seed-index -- ./artifacts/airlock-seed-index.json',
      purpose: 'Compact cross-seed regression table with winners, match lengths, and audit hashes.',
    },
    {
      name: 'Show pack',
      schema: 'airlock.show_pack.stage0.v1',
      format: 'json',
      defaultPath: './artifacts/airlock-show-pack.json',
      generateCommand: 'npm run show-pack',
      verifyCommand: 'npm run verify-show-pack -- ./artifacts/airlock-show-pack.json',
      purpose: "Demo/reviewer pack with multiple seeded matches, pick'em prompts, transcript excerpts, reveal data, and audit hashes.",
    },
  ];
  const catalogCore = {
    schema: 'airlock.artifact_catalog.v1',
    entries,
  } satisfies Omit<ArtifactCatalog, 'catalogHash'>;

  return {
    ...catalogCore,
    catalogHash: digest(catalogCore),
  };
}
